version: '3'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
  web:
    build: .
    volumes:
      - .:/docker_rails
    ports:
      - "3000:3000"
    depends_on:
      - db
#標準入出力とエラー出力をコンテナに結びつける設定
    stdin_open: true
#疑似端末（キーボードによる入力）をコンテナに結びつける設定
    tty: true
    command: dockerize -wait tcp://db:3306 -timeout 20s bundle exec rails s -b 0.0.0.0
    #command: dockerize -wait tcp://db:3306 -timeout 20s bundle exec unicorn -c config/unicorn.rb
volumes:
  mysql-data:
    driver: local